### Remember to change the paths for muscle and hmm tools


#Problem 1
#Align references using muscle
/Users/brittnibertolet/Desktop/bcLectures/Bioinformatics/muscle -in sigma.ref -out sigma.align
/Users/brittnibertolet/Desktop/bcLectures/Bioinformatics/muscle -in sporecoat.ref -out sporecoat.align
/Users/brittnibertolet/Desktop/bcLectures/Bioinformatics/muscle -in transporter.ref -out transporter.align
# Build HMM using hmmbuild
/Users/brittnibertolet/Desktop/bcLectures/Bioinformatics/hmmer/binaries/hmmbuild sigma.hmm sigma.align
/Users/brittnibertolet/Desktop/bcLectures/Bioinformatics/hmmer/binaries/hmmbuild sporecoat.hmm sporecoat.align
/Users/brittnibertolet/Desktop/bcLectures/Bioinformatics/hmmer/binaries/hmmbuild transporter.hmm transporter.align

#loop the search 
for files in sigma.hmm sporecoat.hmm transporter.hmm
do
	for fastas in *.fasta
	do
		/Users/brittnibertolet/Desktop/bcLectures/Bioinformatics/hmmer/binaries/hmmsearch --tblout $files.$fastas.hits $files $fastas	
		cat $files.$fastas.hits | grep -v "#" | awk '{print $1, $3, $5}' >> all.table
	done
done

### Move all the hits somewhere
mkdir hits
mv *.hits hits

### Move all the alignments somewhere
mkdir alignments
mv *.align alignments

### Move all the HMMs somewhere
mkdir HMMs
mv *.hmm HMMs

#### Reformat the table
cat all.table| sed 's/tr\|.*\|.*_9//g' | sed 's/\.ref//g' > final.output

