#Problem 1
#muscle
./muscle -in sigma.ref -out sigma.align
./muscle -in sporecoat.ref -out sporecoat.align
./muscle -in transporter.ref -out transporter.align
#hmm profile
./hmmbuild sigma.hmm sigma.align
./hmmbuild sporecoat.hmm sporecoat.align
./hmmbuild transporter.hmm transporter.align
#loop the search 
for files in sigma.hmm sporecoat.hmm transporter.hmm
do
	for fastas in *.fasta
	do
		./hmmsearch --tblout $files.$fastas.hits $files $fastas	
		cat $files.$fastas.hits | grep -v "#" | awk '{print $1, $3, $6}' > hits.table
	done
done
